// ─── Error Codes ──────────────────────────────────────────

export const UploadErrorCode = {
  ERR_INVALID_MAGIC_BYTES: "ERR_INVALID_MAGIC_BYTES",
  ERR_DURATION_EXCEEDED: "ERR_DURATION_EXCEEDED",
  ERR_FILE_CORRUPTED: "ERR_FILE_CORRUPTED",
  ERR_SIZE_MISMATCH: "ERR_SIZE_MISMATCH",
  ERR_FILE_TOO_LARGE: "ERR_FILE_TOO_LARGE",
  ERR_PRESIGN_EXPIRED: "ERR_PRESIGN_EXPIRED",
  ERR_RATE_LIMITED: "ERR_RATE_LIMITED",
  ERR_QUARANTINE_NOT_FOUND: "ERR_QUARANTINE_NOT_FOUND",
  ERR_DUPLICATE_SONG: "ERR_DUPLICATE_SONG",
  ERR_UNAUTHORIZED: "ERR_UNAUTHORIZED",
  ERR_VALIDATION: "ERR_VALIDATION",
  ERR_USER_NOT_FOUND: "ERR_USER_NOT_FOUND",
  ERR_SERVER_ERROR: "ERR_SERVER_ERROR",
} as const;

export type UploadErrorCode =
  (typeof UploadErrorCode)[keyof typeof UploadErrorCode];